# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BleTest' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add the base RNPermissions pod
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  
  # Try to find the bluetooth permission podspec in different locations
  if File.exist?('../node_modules/react-native-permissions/ios/BluetoothPeripheral')
    pod 'Permission-BluetoothPeripheral', :path => '../node_modules/react-native-permissions/ios/BluetoothPeripheral'
  elsif File.exist?('../node_modules/react-native-permissions/apple/BluetoothPeripheral')
    pod 'Permission-BluetoothPeripheral', :path => '../node_modules/react-native-permissions/apple/BluetoothPeripheral'
  end
  
  # Add vector icons for UI elements
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  # Add file system access for SFTP functionality
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  # Add camera roll access for saving media files
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-camera-roll/camera-roll'
  
  # Add document picker for file selection
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end